export const KRYON_NETWORK_CONFIG = {
  NETWORK: "TESTNET",
  RPC_URL: "https://soroban-testnet.stellar.org",
  NETWORK_PASSPHRASE: "Test SDF Network ; September 2015",
  
  CONTRACTS: {
    KRYON_LIQUIDITY: "CCN2SQ6NA3TBV6EEPYEVTWQ2ORFZB2CXHVHMFEVOHPB2DCOB7IV2XFMX",
    KRYON_ESCROW: "CDGBJGCR5E7YUALEBY7C6MVXSTNN3TW3GWHDQBMZANJKFZM6SVHPHVDO"
  }
};
